# Generated by Django 2.2.1 on 2019-05-14 12:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('implement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchDate',
            new_name='SearchDateModel',
        ),
    ]
