# Generated by Django 2.2.1 on 2019-05-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pass_for_api',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
