# Generated by Django 2.2.1 on 2019-05-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_pass_for_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=75, unique=True),
        ),
    ]
